identifier: l8geh2ydz1hba583
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-posts
homeFolder: /media/moe/Anyway/Projects/my-blog
distFolder: dist/my-posts
outDir: /media/moe/Anyway/Projects/my-blog/dist/static
handle404: ''
allowErrorCollect: true
